---
- name: phpmyadmin installed
  ansible.builtin.apt:
    name: phpmyadmin
    state: latest
- name: phpmyadmin site config in place
  notify: restart nginx
  ansible.builtin.template:
    src: phpmyadmin
    dest: /etc/nginx/sites-enabled
    owner: root
    group: root
    mode: "0644"
- name: phpmyadmin site content ownership correct 
  ansible.builtin.file:
    path: /usr/share/phpmyadmin
    state: directory
    recurse: yes
    owner: www-data
    group: www-data