---
- name: phpmyadmin installed
  ansible.builtin.apt:
    name: phpmyadmin
    state: latest
- name: phpmyadmin site config in place
  notify: restart nginx
  ansible.builtin.template:
    src: phpmyadmin
    dest: /etc/nginx/sites-enabled
    owner: root
    group: root
    mode: "0644"
- name: php 
  ansible.builtin.copy:
    src: default
    dest: /var/www
    owner: www-data
    group: www-data
    mode: "0664"